#!/usr/bin/env python3
"""Cached files marked unread that are shadowed by a pathless record marked extracted.

WHY. 639 source records carry a read_state_basis beginning `derived:`, meaning the state
was inferred from the KB citation graph rather than from anyone opening the document. Only
one of those has a cache file, so the actionable population is not the derived records
themselves but the PAIRS: a file on disk marked unread or skimmed, sitting beside a
pathless record for the same document that the citation graph marked extracted. If they
are the same document, the file was read and its "unread" is bookkeeping noise; the
corpus's unread count is overstated by however many of these there are.

WHY THE RANKING IS BY THE SHADOW'S FACT COUNT. A pathless record cited by many facts was
almost certainly read properly and only its partner's bookkeeping is wrong. One cited by a
single fact is where a document may actually be unread.

**MOST OF THE RAW PAIRS ARE NAME COLLISIONS, NOT DUPLICATES.** The pairing comes from
`duplicate_sources.py --stems`, whose overlap threshold was loosened to 0.75 in 2026-09 to
catch `sgw-ymca-annual-report-1966-67` against "YMCA Montreal Annual Report 1966-67". At
that threshold a corpus full of formulaic names -- `news-release-1964-2`,
`news-release-1970-09-21` -- matches things that share only their shape. So the pairs are
classified here by the dates in the two names: a February 1970 record shadowing a September
1970 release is a collision whatever the stems say. On the first run, 13 of 78 pairs were
provably collisions and 45 could not be decided from the names at all.

**VERIFICATION IS ONE-DIRECTIONAL.** A phrase quoted in a fact that cites the shadow, found
in the cached file, proves they are the same document. NOT finding it proves nothing: the
OCR mangles words, and a multi-source fact may be quoting its other source. So a hit
confirms a pair and a miss leaves it open. Four pairs were confirmed that way on 2026-09-06
and three records updated; the rest stand.

Usage: python3 scripts/reread/derived_duplicates.py
"""
import json
import re
import subprocess
import sys


def ym(s):
    return {(m.group(1), m.group(2)) for m in re.finditer(r"((?:19|20)\d{2})[-_]?(\d{2})?", s)}


def classify(fname, shadow):
    a, b = ym(fname), ym(shadow)
    ya, yb = {y for y, _ in a}, {y for y, _ in b}
    if not ya or not yb:
        return "undecidable from the names"
    if not ya & yb:
        return "COLLISION (years differ)"
    common = ya & yb
    ma = {m for y, m in a if m and y in common}
    mb = {m for y, m in b if m and y in common}
    if ma and mb and not ma & mb:
        return "COLLISION (months differ)"
    return "candidate"


def main():
    out = subprocess.run([sys.executable, "scripts/reread/duplicate_sources.py", "--stems"],
                         capture_output=True, text=True)
    if out.returncode:
        raise SystemExit(out.stderr[-2000:])
    facts = json.load(open("kb/facts.json"))["facts"]
    cites = {}
    for f in facts:
        for s in f.get("sources", []):
            cites[s] = cites.get(s, 0) + 1
    srcs = json.load(open("sources/sources.json"))
    recs = srcs["sources"] if isinstance(srcs, dict) else srcs
    on_disk = {r["source_id"]: r for r in recs if r.get("cache_path")}
    pathless = {r["source_id"]: r for r in recs if not r.get("cache_path")}

    # duplicate_sources.py --stems prints a filename header then its records, one per
    # indented line -- not two ids on one line, which a first version of this parser
    # assumed and so produced an empty report that looked like a clean corpus.
    rows = []
    block = []
    blocks = []
    for line in out.stdout.split("\n") + [""]:
        if line.startswith("    ") and "src_" in line:
            block.append(re.search(r"src_[A-Za-z0-9_]+", line).group(0))
        else:
            if len(block) >= 2:
                blocks.append(block)
            block = []
    for ids in blocks:
        disk = next((i for i in ids if i in on_disk), None)
        shadow = next((i for i in ids if i in pathless), None)
        if not disk or not shadow:
            continue
        dr = on_disk[disk]
        if dr.get("read_state") not in ("unread", "skimmed"):
            continue
        if pathless[shadow].get("read_state") != "extracted":
            continue
        fname = dr["cache_path"].rsplit("/", 1)[-1]
        rows.append((cites.get(shadow, 0), fname, dr.get("read_state"), shadow,
                     classify(fname, shadow)))
    rows.sort()

    print("# Cached files marked unread, shadowed by a pathless record marked extracted\n")
    print("Generated by `scripts/reread/derived_duplicates.py`. Regenerate rather than hand-edit.\n")
    print("Read the module docstring before acting on any row: most raw pairs are NAME")
    print("COLLISIONS, and a failed verification proves nothing.\n")
    for label in ("candidate", "undecidable from the names",
                  "COLLISION (years differ)", "COLLISION (months differ)"):
        sel = [r for r in rows if r[4] == label]
        print("\n## %s (%d)\n" % (label, len(sel)))
        if not sel:
            print("none")
            continue
        print("| Facts citing the shadow | Cached file | State on disk | Shadow record |")
        print("|---|---|---|---|")
        for n, fn, st, sh, _ in sel:
            print("| %d | `%s` | %s | `%s` |" % (n, fn, st, sh))


if __name__ == "__main__":
    main()
